#!/bin/bash

#this is version 2.0

declare -i dif=0
declare -i i=1
declare -i j=0
declare -i k=0
declare -i u=0
declare -i x=0
declare -i y=0
declare -i sum=0
declare -i tot=0

echo "**** ABACUS PRACTICE!!! ****"
echo ""
echo "Enter your degree of difficulty (1-10)"
read dif
((j = dif*dif))

echo "Add this column of numbers"
echo ""
((k=dif+1))

while [ $u -lt $k ]
do
((x= $RANDOM % 256 ))
((y= $RANDOM % 243 ))
((z= ($x * $j) + $y))
printf '%10s\n' $z;
((sum=sum+z))
u=$[$u+1]
done

# echo ""
# echo $sum
# echo ""

echo ""
echo "What is the total?: "
read tot

while (($sum != $tot))
do
if (($sum == $tot));
then
  break
else
  #echo "you are off by" $(($tot-$sum))
  echo "NOPE!"
  echo ""
  echo "try again:"
  read tot
fi
done

echo ""
echo "YOU ARE CORRECT!!!"
echo ""
